spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Baipanuly Askarkhan
  group: IT1-2411IS
  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true
  rate-limit:
    requests-per-minute: 60
    burst: 10

logging:
  level:
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, env, configprops, conditions
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always